name: Build Release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Rename artifact
        run: |
          cp target/*-runner.jar onecx-svc-generator.jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: onecx-svc-generator.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
